### ISSUE TITLE
Build Instructions?

### ISSUE THREAD

**Issue by geoguide** [Nodeclipse/GradleEditor#4]
The repo has been down for days, so I can't still this but I have a dependency on it. Is there any way I could get instructions on how to build the plugin so that I can manually install it?

**Comment by paulvi** [comment]
If you need just install see https://github.com/Nodeclipse/nodeclipse-1/issues/207

if you want to build, see #1 

Can we work on further? I have questions too.

**Comment by paulvi** [comment]
user fears talking. closing
