### ISSUE TITLE
Add licence file

### ISSUE THREAD

**Issue by vogella** [Nodeclipse/GradleEditor#7]
Under which licence is this code developed? EPL?

**Comment by paulvi** [comment]
Nodeclipse has a mixture of Apache, MIT & EPL.

Would any of these 3 above suit you?

And yes this repo should put specific LICENCE inside

**Comment by vogella** [comment]
EPL sounds fitting to me but the licence selection is up to you.

Am 29.08.2016 5:16 vorm. schrieb "Paul Verest" notifications@github.com:

**Comment by paulvi** [comment]
Quickly added as GitHub now has MIT in templates
